version: '3.1'
services:
  ui:
    build: ./ui
    ports:
      - "80:80"
    depends_on:
      - rest
  rest:
    build: ./back
    expose:
      - "3000"
    depends_on:
      - mongo
  mongo:
    image: mongo
